---
baseurl: "https://insomnia.rest/"
languageCode: "en-us"
copyright: "Floating Keyboard Software. Suite 219, 770 Fisgard St, Victoria BC, Canada"
title: "Insomnia REST Client"
theme: "hugo-insomnia-theme"
publishdir: "_hugo"
disqusShortname: "insomnia-rest"
googleAnalytics: "UA-9837747-12"
permalinks:
  documentation: /documentation/:slug
menu:
  main:
    - Name: "Pricing"
      Identifier: "pricing"
      URL: "/pricing/"
      Weight: 20
    - Name: "Download"
      Identifier: "download"
      URL: "/download/"
      Weight: 0
    - Name: "Docs"
      Identifier: "docs"
      URL: "/documentation/"
      Weight: 10
    - Name: "Blog"
      Identifier: "blog"
      URL: "/blog/"
      Weight: 40
  footer:
    - Name: "Licence"
      Identifier: "eula"
      URL: "/eula/"
    - Name: "Changelog"
      Identifier: "changelog"
      URL: "/changelog/"
    - Name: "Support"
      Identifier: "support"
      URL: "/documentation/support-and-feedback/"
      weight: -1
  docs:
      - Name: ""
        Identifier: "welcome"
        Weight: 0
      - Name: "Getting Started"
        Identifier: "starting"
        Weight: 1
      - Name: "Help Topics"
        Identifier: "topics"
        Weight: 2
      - Name: "Other"
        Identifier: "other"
        Weight: 3
author:
  name: "Gregory Schier"
  image: "me.jpg"
taxonomies:
  tag: "tags"
  category: "categories"
params:
  copyrightURL: "https://floatingkeyboard.com"
  docsCategories:
    - "welcome"
    - "starting"
    - "topics"
  stylesheets:
    - "main.css"
  scripts:
    - "main.js"
  email: "support@insomnia.rest"
  pageNotFoundTitle: "Sorry, that page doesn't exist"
  shortName: "Insomnia 3.0"
  bio: "Independant software developer"
  location: "Victoria BC, Canada"
  description: "A powerful REST API Client with cookie management, environment variables, code generation, and authentication for Mac, Window, and Linux"
  twitter: "GetInsomnia"
  googlePlus: "InsomniaRest"
  keepReadingStr: "Read More"
pygmentsCodeFences: true
pygmentsStyle: "monokai"
pygmentsUseClasses: true
metaDataFormat: "yaml"
blackfriday:
  fractions: false
