---
baseurl: "https://insomnia.rest/"
languageCode: "en-us"
copyright: "Insomnia REST Client"
title: "Insomnia REST Client"
theme: "hugo-schier-theme"
publishdir: "_dist"
disqusShortname: "insomnia-rest"
googleAnalytics: "UA-9837747-12"
permalinks:
  documentation: /documentation/:slug
menu:
  main:
    - Name: "Blog"
      Identifier: "blog"
      URL: "/blog"
      Weight: 2
    - Name: "Download"
      Identifier: "download"
      URL: "/download/"
      Weight: 0
    - Name: "Docs"
      Identifier: "docs"
      URL: "/documentation/"
      Weight: 1
  docs:
      - Name: ""
        Identifier: "welcome"
        Weight: 0
      - Name: "Getting Started"
        Identifier: "starting"
        Weight: 1
      - Name: "Help Topics"
        Identifier: "topics"
        Weight: 2
author:
  name: "Gregory Schier"
  image: "me.jpg"
taxonomies:
  tag: "tags"
  category: "categories"
params:
  docsCategories:
    - "welcome"
    - "starting"
    - "topics"
  stylesheets:
    - "main.css"
  scripts:
    - "main.js"
  email: "support@insomnia.rest"
  pageNotFoundTitle: "Sorry, that page doesn't exist"
  shortName: "Insomnia 3.0"
  bio: "Independant software developer"
  location: "Victoria BC, Canada"
  description: "A simple yet powerful REST API Client with cookie management, environment variables, code generation, and authentication for Mac, Window, and Linux"
  twitter: "GetInsomnia"
  googlePlus: "InsomniaRest"
  keepReadingStr: "Read More"
pygmentsCodeFences: true
pygmentsStyle: "monokai"
pygmentsUseClasses: true
metaDataFormat: "yaml"
blackfriday:
  fractions: false
